#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Oct 31 11:47:02 2016

@author: Andrew Alferman and Dan Magee
"""

import numpy as np
import matplotlib.pyplot as plt

scatterpoints = 10000

X, Y, Z = [], [], []
for i in range(scatterpoints):
    phi = i / scatterpoints * 2 * np.pi
    C = [1/6, 1/2, 1, 1 - (np.cos(phi) + 1j*np.sin(phi))]
    roots = np.roots(C)
    X.append(roots[0])
    Y.append(roots[1])
    Z.append(roots[2])

plt.scatter(np.real(X), np.imag(X), color='red',
            marker='.', linewidths=0.00001)
plt.scatter(np.real(Y), np.imag(Y), color='blue',
            marker='.', linewidths=0.00001)
plt.scatter(np.real(Z), np.imag(Z), color='green',
            marker='.', linewidths=0.00001)
plt.xlabel(r'$\lambda_R$' + 'Value', fontsize=12)
plt.ylabel(r'$\lambda_I$' + 'Value', fontsize=12)
plt.title('Stability Region of RK3 Scheme', fontsize=14)
plt.grid(b=True, which='both', color='black')
plt.show()
